### ISSUE TITLE
after adding this module, upload to app store fails with 'invalid swift support'

### ISSUE THREAD

**Issue by DaveAndersonxx** [master-atul/react-native-appstore-version-checker#12]
Invalid Swift Support - The expected dylibs are missing from the app’s Framework location...

build completes fine.  able to run the app in a simulator.  cannot deploy update to app store, though, because of the above error.

suggestions?

thanks.

**Comment by master-atul** [comment]
Hmm. The interesting part is that this module doesn't contain any native ios part. There isn't even an ios folder in the source code. Its pure js for IOS. since I just fetch the data and manipulate it completely in JS. 

Can you check if while doing react native link, did it add any ios specific native changes to your project? 

This module should not cause the error you are facing.

**Comment by DaveAndersonxx** [comment]
Thanks for the reply.  You're right - it's got absolutely nothing to do with version-checker.  I don't know what happened, but Apple is rejecting my builds with that error every time now.  Thanks, anyway.
