### ISSUE TITLE
CertPathValidatorException

### ISSUE THREAD

**Issue by chhornchandy** [master-atul/react-native-appstore-version-checker#20]
Dear Beloved.
I got error 👎 
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by master-atul** [comment]
Hi 👋 
This issue doesnt look like its related to this module.
Seems to me like: 
1. You have a custom SSL certficate configuration somewhere and the certificate might have expired.
2. You are using a SSL proxy and the android app doesnt trust the certificate.

In any case the issue seems to be related to you SSL certficate configuration and not this module.
You might get some help here: https://stackoverflow.com/questions/6825226/trust-anchor-not-found-for-android-ssl-connection
